spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      #      jdbc-url: jdbc:mariadb://localhost:3306/mydb
      username: '{cipher}625beab0ee0bb8ab8fd65b9b5c790e0a375b007c651b5bdaa2f7547f7491744c'
      password: '{cipher}285bd1d3c0d2303f54d5111458d53a96578bfe5f261b49670ef965b993a0311e'

token:
  expiration_time: 86400000
  secret: user_token_default
gateway:
  ip: 172.18.0.5
#192.168.219.0/24

order_service:
  url: http://ORDER-SERVICE/{userId}/orders
  exception:
    orders_is_empty: User's orders is empty.